#####################
## BASE INSTALL STAGE
FROM node:lts AS install-base
WORKDIR /usr/src/
COPY .yarn ./.yarn
COPY .yarnrc.yml .
COPY yarn.lock .
COPY package.json .

# copy and install all workspace packages
RUN yarn plugin import workspace-tools

# SERVER STAGES
FROM install-base AS install-server

# copy and install all workspace packages
COPY ./server/package.json ./server/package.json
RUN yarn workspaces focus server

FROM install-server AS develop-server
COPY ./server ./server

EXPOSE 8080
CMD ["yarn", "workspace", "server", "docker"]

# CLIENT STAGES
FROM install-base AS install-client
COPY ./client/package.json ./client/package.json 
RUN yarn workspaces focus client

FROM install-client as develop-client
COPY ./client ./client

ENV DOCKER "true"

EXPOSE 3000
CMD ["yarn", "workspace", "client", "dev"]