#####################
## BASE INSTALL STAGE
FROM node:lts AS install
WORKDIR /usr/src/
COPY .yarn ./.yarn
COPY .yarnrc.yml .
COPY yarn.lock .
COPY package.json .

# copy and install all workspace packages
RUN yarn plugin import workspace-tools

FROM install AS develop
COPY . .
RUN yarn install

EXPOSE 3000
EXPOSE 8080
CMD ["yarn", "local"]