#####################
## BASE INSTALL STAGE
FROM node:lts AS install-base
WORKDIR /usr/src/
COPY .yarn ./.yarn
COPY .yarnrc.yml .
COPY yarn.lock .
COPY package.json .

# copy and install all workspace packages
RUN yarn plugin import workspace-tools

# DEVELOPMENT BUILD
FROM install-base AS develop-server
COPY ./server ./server
RUN yarn workspace server install

EXPOSE 8080
CMD ["yarn", "workspace", "server", "dev"]

FROM install-base AS develop-client
COPY ./client ./client
RUN yarn workspace client install

EXPOSE 3000
CMD ["yarn", "workspace", "client", "dev"]