# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI


on:
  pull_request:
    branches: [ main, dev ]

jobs:
  frontend-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: GitHub Checks
      uses: LouisBrunner/checks-action@v1.1.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test Frontend
        conclusion: ${{ job.status }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn workspace client install
    - run: yarn workspace client build
    - run: yarn workspace client test
    
  backend-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: GitHub Checks
      uses: LouisBrunner/checks-action@v1.1.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test Frontend
        conclusion: ${{ job.status }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn workspace server install
    - run: yarn workspace server build
    - run: yarn workspace server test

  